;EQUs for this game
STARTY			EQU	6
STARTX			EQU 1
MINYPOS			EQU 1
MAXYPOS			EQU	22
MINXPOS			EQU 0
MAXXPOS			EQU 29
MAXBATX			EQU 27
DISPLEN			EQU 33
STARTBATY		EQU 21
BOUNCEBAT		EQU 19
BALLSPEED		EQU	4
VSYNCLP			EQU 2
TEXTFRAMES		EQU 16
FINALFRAMES		EQU 48

